apiVersion: v1
kind: Service
metadata:
    name: "testdc-0b3d"
    labels:
        app: "testdc-0b3d"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "testdc-0b3d"